  - name: Create /opt/ssl directory for certificates
    become: true
    file: path=/opt/ssl state=directory mode=0755

  - name: Create self signed certificate
    become: true
    command: openssl genrsa -out ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com.key 2048
    args:
     chdir: /opt/ssl

  - name: Create self signed certificate
    become: true
    command: openssl req -new -x509 -key ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com.key -out ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com.cert -days 3650 -subj /CN=ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com
    args:
     chdir: /opt/ssl

  - name: NGINX | Installing NGINX
    become: true
    yum:
      name: nginx
      state: latest

  - name: NGINX | Nginx nginx.conf config file
    become: true
    tempalte: 
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0644
    notify:
      - reload nginx

  - name: NGINX | Nginx jenkins.conf Config file
    become: true
    tempalte: 
      src: jenkins.conf
      dest: /etc/nginx/conf.d/jenkins.conf
      owner: root
      group: root
      mode: 0644
    notify:
     - reload nginx

  - name: NGINX | Starting NGINX
    become: true
    service:
      name: nginx
      state: started
