  - name: Create /opt/ssl directory for certificates
    become: true
    file: path=/opt/ssl state=directory mode=0755

  - name: Create self signed certificate
    become: true
    command: openssl genrsa -out ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com.key 2048
    args:
     chdir: /opt/ssl

  - name: Create self signed certificate
    become: true
    command: openssl req -new -x509 -key ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com.key -out ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com.cert -days 3650 -subj /CN=ec2-52-63-169-195.ap-southeast-2.compute.amazonaws.com
    args:
     chdir: /opt/ssl
